// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBSrpWGjaU74FGYLtC8SAtXgznHS-CDzs',
    appId: '1:880024356807:web:caae9e6e6ddabb9348fbe2',
    messagingSenderId: '880024356807',
    projectId: 'golfclapp-e7ee0',
    authDomain: 'golfclapp-e7ee0.firebaseapp.com',
    storageBucket: 'golfclapp-e7ee0.appspot.com',
    measurementId: 'G-BEC79K20XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAelOxLm16rxZpabm3c08oi-1x0VkOpy5Y',
    appId: '1:880024356807:android:fa6ed059e40bca9748fbe2',
    messagingSenderId: '880024356807',
    projectId: 'golfclapp-e7ee0',
    storageBucket: 'golfclapp-e7ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe99pYzMw1WC66Sqe_PVnDO_DECj6KcjM',
    appId: '1:880024356807:ios:0a6b941f70fb9da948fbe2',
    messagingSenderId: '880024356807',
    projectId: 'golfclapp-e7ee0',
    storageBucket: 'golfclapp-e7ee0.appspot.com',
    iosClientId: '880024356807-787seiua5a2f96jo5ec40tuk7dh2k85o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe99pYzMw1WC66Sqe_PVnDO_DECj6KcjM',
    appId: '1:880024356807:ios:67626937a45403c248fbe2',
    messagingSenderId: '880024356807',
    projectId: 'golfclapp-e7ee0',
    storageBucket: 'golfclapp-e7ee0.appspot.com',
    iosClientId: '880024356807-v25qu4gu7ihk2j7s9q636slvlimu7lqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
